from abc import ABC, abstractmethod
from .file_download import FileDownload

class Downloader(ABC):
    @abstractmethod
    def download(self, file: FileDownload) -> bool: ...
    def confirm(self, file: FileDownload, remote_file_size: int) -> bool: ...
    def prepare_download(self, file: FileDownload): ...
